feat: implement license update status

diff --git a/task b/task
--- a/task
+++ b/task
@@ -2,58 +2,71 @@
 set -e
 
 if [[ -a ".env" ]]; then
-    export $(cat .env | sed 's/#.*//g' | xargs)
+    export $(cat .env | sed 's/^#.*//g' | xargs)
 fi
-
-# Generate module list
-: ${EXCLUDE:='license_ocad,license_sale,license_website'}
-: ${MODULES:=$(find . -type f -name "__manifest__.py" | xargs dirname | xargs -n1 basename | sort -u | tr '\n' ',')}
-for MODULE in $(echo $EXCLUDE | sed "s/,/ /g")
-do
-    MODULES=$(echo $MODULES | sed s/$MODULE,//)
-done
-MODULES=$(echo $MODULES | sed 's/,$//g')
-
-
-function setup() {
-    docker-compose up -d
-}
-
-function test() {
-    echo "Test modules: $MODULES"
-    docker-compose exec -T odoo odoo -d odoo -i $MODULES --stop-after-init --test-tags /$MODULES
-}
-
-function kill() {
-    docker-compose down -v
-}
 
 function help() {
     echo
-    echo "$1 <command> [options]"
+    echo "task <command> [options]"
     echo
     echo "commands:"
     echo
-    column -t -s"|" ./task.md | tail -n +4
+
+    # Define column widths
+    cmd_width=10
+    opt_width=6
+    desc_width=32
+
+    # Print table header
+    printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "Command" "Option" "Description"
+    echo "|$(printf '%*s' $((cmd_width + 2)) '' | tr ' ' '-')|$(printf '%*s' $((opt_width + 2)) '' | tr ' ' '-')|$(printf '%*s' $((desc_width + 2)) '' | tr ' ' '-')|"
+
+    # Print table rows
+    printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "all" "" "Run all tasks."
+    printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "version" "" "Show version of required tools."
+    printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "init" "" "Init local env."
+    printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "lint" "" "Run pre-commit."
+
     echo
 }
 
+function version() {
+    python3 -V
+    pip -V
+}
+
+function init() {
+    echo "Install python dependencies"
+    python3 -m venv env
+    source env/bin/activate
+    pip install pre-commit
+}
+
+function lint() {
+    echo "Run pre-commit"
+    source env/bin/activate
+    pre-commit run --all-files # --show-diff-on-failure --color=always
+}
+
 case "$1" in
+    help)
+        help
+        ;;
     all)
-        setup
-        test
-        kill
+        version
+        init
+        lint
         ;;
-    setup)
-        setup
+    version)
+        version
         ;;
-    test)
-        test
+    init)
+        init
         ;;
-    kill)
-        kill
+    lint)
+        lint
         ;;
     *)
-        help task
-        exit 1
+        help
+        exit 1;
 esac
