feat(license_sale): pricelist

diff --git a/task b/task
--- a/task
+++ b/task
@@ -2,7 +2,7 @@
 set -e
 
 if [[ -a ".env" ]]; then
-    export $(cat .env | sed 's/^#.*//g' | xargs)
+    source .env
 fi
 
 function help() {
@@ -23,21 +23,21 @@ function help() {
 
     # Print table rows
     printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "all" "" "Run all tasks."
-    printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "version" "" "Show version of required tools."
-    printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "init" "" "Init local env."
-    printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "lint" "" "Run pre-commit and update index.html."
+    printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install" "" "Setup the local environment."
+    printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "lint" "" "Run pre-commit."
+    printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "docs" "" "Updte index.html."
     printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "source" "" "Source the Python virtual env."
+    printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "version" "" "Show version of required tools."
 
     echo
 }
 
 function version() {
     uv --version
-    python3 -V
 }
 
-function init() {
-    echo "Install python dependencies"
+function install() {
+    echo "Setup venv and install python dependencies"
     uv venv env
     source env/bin/activate
     uv pip install pre-commit rst2html5
@@ -48,6 +48,11 @@ function lint() {
 
     echo "Run pre-commit"
     pre-commit run --all-files # --show-diff-on-failure --color=always
+
+}
+
+function docs() {
+    source env/bin/activate
 
     echo "Update index.html for all modules"
     for MODULE in ./*; do
@@ -60,28 +65,26 @@ function lint() {
 
 }
 
-case "$1" in
-    help)
-        help
-        ;;
-    all)
-        version
-        init
-        lint
-        ;;
-    version)
-        version
-        ;;
-    init)
-        init
-        ;;
-    lint)
-        lint
-        ;;
-    source)
-        source env/bin/activate
-        ;;
-    *)
-        help
-        exit 1;
-esac
+if declare -f "$1" > /dev/null; then
+    "$1" "${@:2}"
+else
+    case "$1" in
+        help)
+            help task
+            exit 1
+            ;;
+        all)
+            install
+            lint
+            doc
+            ;;
+        source)
+            source env/bin/activate
+            ;;
+        *)
+            echo "Unknown command: $1"
+            help task
+            exit 1
+            ;;
+    esac
+fi
